/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Demo01VanillaJs": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Demo02VuejseSpa": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "LunchFinderApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Slides": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}